<?xml version="1.0" encoding="utf-8"?><Database Name="ditipTravel" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6RN9JQE\SQLEXPRESS;Initial Catalog=ditipTravel;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ditipTravelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_Person" Member="tbl_Persons">
    <Type Name="tbl_Person">
      <Column Name="id" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="surname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>